SELECT * FROM CLIENTE;

SELECT CNPJ FROM CLIENTE;

SELECT CNPJ, SUBSTR(CNPJ, 1, 3) FROM CLIENTE;

SELECT CNPJ, SUBSTR(CNPJ, 1, 3), SUBSTR(CNPJ, 4, 2) FROM CLIENTE;

SELECT CNPJ, SUBSTR(CNPJ, 1, 3) ||'/' || SUBSTR(CNPJ, 4, 2) || '-' || SUBSTR(CNPJ, 6) AS CNPJ_FORMAT FROM CLIENTE;