SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO,
NF.CPF AS CPF_DA_NOTA,
TC.NOME AS NOME_DO_CLIENTE,
NF.CPF AS CPF_DA_NOTA
FROM
TABELA_DE_CLIENTES TC

INNER JOIN 
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF


SELECT COUNT(*)FROM TABELA_DE_CLIENTES

