--criar tabelas

CREATE TABLE TB_CLIENTES 
(
    CPF VARCHAR2(11),
    NOME VARCHAR (100),
    ENDERECO1 VARCHAR2 (150),
    ENDERECO2 VARCHAR2 (150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2 (50),
    ESTADO VARCHAR2 (2),
    CEP VARCHAR2 (8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR(1),
    LIMITE_CREDITO NUMBER (15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1) 
);

CREATE TABLE TB_VENDEDORES
(
    MATRICULA VARCHAR2 (5),
    NOME VARCHAR2(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER
    
);

CREATE TABLE TB_PRODUTOS

(
    PRODUTO VARCHAR2 (20),
    NOME VARCHAR2 (150),
    EMBALAGEM VARCHAR2 (50),
    TAMANHO VARCHAR2 (50),
    SABOR VARCHAR2 (50),
    PRECO_LISTA NUMBER
    
);


--visualizar tabela
SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_VENDEDORES;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_CLIENTES;

--inserir valores nas tabelas

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040107', 'Light - 350 ml - Melancia', 'Lata', '350 ml', 'Melancia', 4.56);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00233', 'João Geraldo da Fonseca', '01/12/2015', 0.10);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1037797','Clean - 2 Litros - Laranja', 'PET','2 Litros','Laranja',16.01);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1000889','Sabor da Montanha - 700 ml - Uva', 'Garrafa','700 ml','Uva',6.31);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1004327','Videira do Campo - 1,5 Litros - Melância', 'PET','1,5 Litros','Melância',19.51);

-- Alterar dados da tabela

UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata'
WHERE PRODUTO = '1037797';

UPDATE TB_PRODUTOS SET 
NOME = 'Clean - 350 ml - Laranja', TAMANHO = '350 ml',
PRECO_LISTA = 5.50 WHERE PRODUTO = '1037797';

--inserindo uma chave primária!

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS 
PRIMARY KEY (PRODUTO);

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES 
PRIMARY KEY (CPF);








)