CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, SOMA_PRECO FROM VW_SOMA_EMBALAGENS 
WHERE SOMA_PRECO >= 80;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS TP
INNER JOIN VW_SOMA_EMBALAGENS VW
ON TP.EMBALAGEM = VW.EMBALAGEM
WHERE VW.SOMA_PRECO >= 80;

--------------------

SELECT 
    NF.CPF, 
    EXTRACT (YEAR FROM NF.DATA_VENDA),
    INF.QUANTIDADE
    
FROM
NOTAS_FISCAIS NF

INNER JOIN
ITENS_NOTAS_FISCAIS INF

ON NF.NUMERO = INF.NUMERO;


SELECT 
    NF.CPF, 
    TO_CHAR (NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
    INF.QUANTIDADE
FROM
NOTAS_FISCAIS NF

INNER JOIN
ITENS_NOTAS_FISCAIS INF

ON NF.NUMERO = INF.NUMERO;

--AGRUPAR

SELECT 
    NF.CPF, 
    TO_CHAR (NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
    SUM(INF.QUANTIDADE) AS SOMA_QTDE
FROM
NOTAS_FISCAIS NF

INNER JOIN
ITENS_NOTAS_FISCAIS INF

ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, TO_CHAR (NF.DATA_VENDA, 'MM-YYYY');

---------------------------------
SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;

--fazendo consulta
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.SOMA_QTDE,
CASE WHEN TC.VOLUME_DE_COMPRA >= TV.SOMA_QTDE THEN 'VENDAS VÁLIDAS'
     WHEN TC.VOLUME_DE_COMPRA < TV.SOMA_QTDE THEN 'VENDAS INVÁLIDAS' END AS STATUS
FROM
    TABELA_DE_CLIENTES TC

INNER JOIN
(
SELECT 
    NF.CPF, 
    TO_CHAR (NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
    SUM(INF.QUANTIDADE) AS SOMA_QTDE
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, TO_CHAR (NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TV.CPF = TC.CPF
ORDER BY STATUS;

