-- PEQUENO FATURA ATÉ 10000
-- MÉDIO ENTRE 10001 E 50000
-- MÉDIO GRANDE ENTRE 50001 E 100000
-- GRANDE MAIS DE 100000

SET SERVEROUTPUT ON 

DECLARE 
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type := 5000;
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
   IF v_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF v_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF v_FATURAMENTO <= 100000 THEN
        v_CATEGORIA := 'MEDIO GRANDE';
    ELSE 
        v_CATEGORIA := 'GRANDE';
   END IF;
   dbms_output.put_line('A Categoria é ' || v_CATEGORIA);
END;


--------------------------------------------------------------------------------
--FUNCTION

CREATE OR REPLACE FUNCTION categoria_cliente
(p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%type)
RETURN
   CLIENTE.CATEGORIA%type
IS 
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
    IF p_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF p_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF p_FATURAMENTO <= 100000 THEN
        v_CATEGORIA := 'MEDIO GRANDE';
    ELSE 
        v_CATEGORIA := 'GRANDE';
   END IF;
   RETURN V_CATEGORIA;
END;

VARIABLE g_CATEGORIA VARCHAR2(100);
EXECUTE : g_CATEGORIA := categoria_cliente(10000);
PRINT g_CATEGORIA;

-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN

    v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

    INSERT INTO CLIENTE
    VALUES
    (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
    COMMIT;
END;

EXECUTE incluir_cliente(2, 'SUPERMERCADO DO VALE', '1111111111', 1, 90000);

EXECUTE incluir_cliente(3, 'SUPERMERCADO CARIOCA', '2222222222', 1, 30000);

SELECT * FROM CLIENTE;