--para exibir a saída
SET SERVEROUTPUT ON;

DECLARE
v_ID SEGMERCADO.ID%type := 1;
v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN 
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
    DBMS_OUTPUT.PUT_LINE (v_DESCRICAO);
END;

DECLARE
v_ID SEGMERCADO.ID%type := 1;
v_IDSaida SEGMERCADO.ID%type;
v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN 
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
    SELECT ID INTO v_IDSaida FROM SEGMERCADO WHERE ID = v_ID;
    DBMS_OUTPUT.PUT_LINE (v_DESCRICAO);
    DBMS_OUTPUT.PUT_LINE (v_IDSaida);
END;