DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 4;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
BEGIN 
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID,UPPER (v_DESCRICAO));
    COMMIT;
END;    

select * from SEGMERCADO;

SELECT * FROM SEGMERCADO WHERE UPPER (DESCRICAO) = 'ATACADO'

DELETE FROM SEGMERCADO WHERE ID = 4;