CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type,
p_CATEGORIA CLIENTE.CATEGORIA%type
)
IS
BEGIN 
    INSERT INTO CLIENTE
    VALUES
    (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, p_CATEGORIA);
    COMMIT;

END;

SELECT * FROM CLIENTE;

EXECUTE incluir_cliente (1, 'SUPERMERCADOS CAMPEAO', '1234567890', 1, 90000, 'MEDIO GRANDE');


---------------------------------------------------------------------------------
--desafio
CREATE OR REPLACE PROCEDURE incluindo_dados_venda
(
    p_ID PRODUTO_VENDA_EXERCICIO.ID%type,
    p_COD_PRODUTO PRODUTO_VENDA_EXERCICIO.COD_PRODUTO%type,
    p_QUANTIDADE PRODUTO_VENDA_EXERCICIO.QUANTIDADE%type,
    p_PRECO PRODUTO_VENDA_EXERCICIO.PRECO%type,
    p_VALOR_TOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%type,
    p_PERCENTUAL PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%type
)
IS 
BEGIN 
    INSERT INTO PRODUTO_VENDA_EXERCICIO
    VALUES
    (p_ID, p_COD_PRODUTO, SYSDATE, p_QUANTIDADE, p_PRECO, p_VALOR_TOTAL, p_PERCENTUAL );
    COMMIT;
END;

SELECT * FROM PRODUTO_VENDA_EXERCICIO


EXECUTE incluindo_dados_venda (1, '41232', 100, 10, 1000, 10);