INSERT INTO SEGMERCADO (ID, DESCRICAO)
VALUES (1, 'Varejo');

SELECT * FROM SEGMERCADO;
DELETE FROM SEGMERCADO;

DECLARE 
v_ID NUMBER(5) := 2;
v_DESCRICAO VARCHAR2 (100) := 'Industria';
BEGIN 
    INSERT INTO SEGMERCADO  (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO);
    COMMIT;
END;