DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 2;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Industrial';
BEGIN 
    UPDATE SEGMERCADO SET DESCRICAO = UPPER (v_DESCRICAO) WHERE ID = v_ID;
    v_ID := 2;
    v_DESCRICAO := 'Industrial';
    
    COMMIT;
END;    

SELECT * FROM SEGMERCADO;

DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 5;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Esportistas';
BEGIN 
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID,UPPER (v_DESCRICAO));
    COMMIT;
END;    

DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 5;
BEGIN 
    DELETE FROM SEGMERCADO WHERE ID = v_ID;
    COMMIT;
END;  
--------------------------------------------------------------------------------

--INCLUSAO DE SEGMENTO

DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 4;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacado';
BEGIN 
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID,UPPER (v_DESCRICAO));
    COMMIT;
END;    

--ALTERAÇÃO DE SEGMENTO

DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 3;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Atacadista';
BEGIN 
    UPDATE SEGMERCADO SET DESCRICAO = UPPER (v_DESCRICAO) WHERE ID = v_ID;
    COMMIT;
END;    

-- EXCLUSÃO DE SEGMENTO 

DECLARE 
    v_ID SEGMERCADO.ID%TYPE := 5;
BEGIN 
    DELETE FROM SEGMERCADO WHERE ID = v_ID;
    COMMIT;
END;  



