--CRIAR TABELA

  CREATE TABLE "TABELA_DE_VENDEDORES_FONTE" 
   ("MATRICULA" NVARCHAR2(5), 
	"NOME" NVARCHAR2(100), 
	"PERCENTUAL_COMISSAO" FLOAT(126), 
	"DATA_ADMISSAO" DATE, 
	"DE_FERIAS" NUMBER(1,0), 
	"BAIRRO" NVARCHAR2(50)
   );

Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00235','Marcio Almeida Silva','0,08',to_date('15/08/14','DD/MM/RR'),'0','Tijuca');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00236','Claudia Morais','0,08',to_date('17/09/13','DD/MM/RR'),'1','Jardins');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00237','Roberta Martins','0,11',to_date('18/03/17','DD/MM/RR'),'1','Copacabana');
Insert into TABELA_DE_VENDEDORES_FONTE (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS,BAIRRO) values ('00238','Pericles Alves','0,11',to_date('21/08/16','DD/MM/RR'),'0','Santo Amaro');
INSERT INTO TABELA_DE_PRODUTOS_FONTE 
VALUES ('9999999', 'NOVO PRODUTO', 'PET', '1 Litro', 'Melancia', 10.2);

SELECT * FROM VENDEDORES V;
SELECT * FROM TABELA_DE_VENDEDORES_FONTE TVF;


--fazendo inner join entre tabelas e utilizando função substr
SELECT 
V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE, 
V.FERIAS AS FERIAS_VENDEDORES, TVF. DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3);

UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 0 WHERE MATRICULA IN ('00236', '00237');
UPDATE TABELA_DE_VENDEDORES_FONTE SET DE_FERIAS = 1 WHERE MATRICULA IN ('00235', '00238');

--------------------------------------------------------------------------------
--exists

SELECT 
V.MATRICULA AS MATRICULA_VENDEDORES,
V.FERIAS AS FERIAS_VENDEDORES
FROM VENDEDORES V
WHERE EXISTS 
(SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3));

--criando vendedor novo
INSERT INTO TABELA_DE_VENDEDORES_FONTE 
VALUES ('00239', 'Jose Maria', 0.12, TO_DATE('2018-01-01', 'YYYY-MM-DD'), 1, 'Tijuca')

--query de inner join
SELECT 
V.MATRICULA AS MATRICULA_VENDEDORES, TVF.MATRICULA AS MATRICULA_FONTE, 
V.FERIAS AS FERIAS_VENDEDORES, TVF. DE_FERIAS AS FERIAS_FONTE
FROM VENDEDORES V
INNER JOIN TABELA_DE_VENDEDORES_FONTE TVF
ON V.MATRICULA = SUBSTR(TVF.MATRICULA, 3,3);


INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('100089', 'Sabor da Montanha - 700 ml - Uva', 'Uva', '700 ml', 'Garrafa', 6.309);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('100090', 'Del Valle Laranja', 'Laranja', '350 ml', 'Lata', 3.50);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('100091', 'Coca Cola', 'Cola', '2 Litros', 'Pet', 8.00);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('100092', 'Guarana Antarctica', 'Guarana', '350 ml', 'Lata', 4.00);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('100093', 'Agua Mineral', 'Sem Gás', '500 ml', 'Pet', 2.00);


