SELECT * FROM TAB_FATURAMENTO;

SELECT * FROM NOTAS;
UPDATE ITENS_NOTAS SET QUANTIDADE = 1000 WHERE NUMERO = '005';

DELETE FROM ITENS_NOTAS WHERE NUMERO = '005';
DELETE FROM NOTAS WHERE NUMERO = '005';

CREATE OR REPLACE TRIGGER TG_TAB_FATURAMENTO
AFTER INSERT OR UPDATE OR DELETE ON ITENS_NOTAS
BEGIN 
DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM
NOTAS N
INNER JOIN
ITENS_NOTAS ITN
ON N.NUMERO = ITN.NUMERO
GROUP BY N.DATA_VENDA;
END;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('007', TO_DATE('2019-01-03','YYYY-MM-DD'), '1471156710', '235', 0.1);

INSERT INTO ITENS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('007', '100089', 40, 10);


UPDATE ITENS_NOTAS SET QUANTIDADE = 1000 WHERE NUMERO = '007';

DELETE FROM ITENS_NOTAS WHERE NUMERO = '007';
DELETE FROM NOTAS WHERE NUMERO = '007';

